### ISSUE TITLE
[FEATURE] Add wrapper for Theta model from statsmodels

### ISSUE THREAD

**Issue by pavelkrizek** [heidelbergcement/hcrystalball#33]
**Is your feature request related to a problem? Please describe.**
I would like to see the Theta forecasting model of Assimakopoulos and Nikolopoulos (2000) in hcrystalball. This method also performed particularly well in forecasting competitions (M3) and it can be of interest for other practitioners

**Describe the solution you'd like**
Have wrapper for Theta model from statsmodels https://www.statsmodels.org/dev/generated/statsmodels.tsa.forecasting.theta.ThetaModel.html#statsmodels.tsa.forecasting.theta.ThetaModel with a unified interface.

**Comment by MichalChromcak** [comment]
Good idea, let's add it.

As discussed (to also track it here), the statsmodels library does not guarantee (yet?) uniform interface for all the models, thus creating new `ThetaWrapper`, that inherits from [`BaseSmoothingWrapper`](https://github.com/heidelbergcement/hcrystalball/blob/master/src/hcrystalball/wrappers/_smoothing.py#L21) in a similar way as [`ExponentialSmoothingWrapper`](https://github.com/heidelbergcement/hcrystalball/blob/master/src/hcrystalball/wrappers/_smoothing.py#L100) does should be preferred over creating factory function `get_statsmodels_wrapper` similar to [`get_sklearn_wrapper`](https://github.com/heidelbergcement/hcrystalball/blob/master/src/hcrystalball/wrappers/_sklearn.py#L271).

**Comment by MichalChromcak** [comment]
ThetaModel will be available in release 0.12 - let's implement it once done along with the migration of other models
https://github.com/statsmodels/statsmodels/milestone/14
